try newer pixel

diff --git a/.github/workflows/android_emu.yml b/.github/workflows/android_emu.yml
--- a/.github/workflows/android_emu.yml
+++ b/.github/workflows/android_emu.yml
@@ -7,6 +7,22 @@ on:
     branches: [ "master" ]
 
 jobs:
+
+  list-avds:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Accept Licenses
+        run: yes | sdkmanager --licenses
+
+      - name: Show System Images
+        run: sdkmanager --list
+
+      - name: Show AVD Devices
+        run: |
+          echo "Try avdmanager:"
+          ${ANDROID_HOME}/cmdline-tools/latest/bin/avdmanager list device || echo "avdmanager not found or missing JAXB"
+
   instrumented-tests:
     runs-on: ubuntu-latest
 
@@ -20,13 +36,15 @@ jobs:
           distribution: 'temurin'
           java-version: 17
 
+
+
       - name: Run Instrumented Tests on Emulator
         uses: ReactiveCircus/android-emulator-runner@v2
         with:
           api-level: 33
           target: google_apis
           arch: x86_64
-          profile: Pixel_2
+          profile: Pixel_4
           emulator-options: -no-window -no-audio -no-snapshot
           disable-animations: true
           script: ./gradlew connectedDebugAndroidTest
